import * as bluprint from "../JAVASCRIPT/Store_Blueprint.js";
import {} from "../JAVASCRIPT/Nav&Footer_Blueprint.js";

// Product Attributes
bluprint.price.insertAtHead(24.99);
bluprint.price.insertAtHead(15.99);
bluprint.price.insertAtHead(34.99);
bluprint.price.insertAtHead(34.99);
bluprint.price.insertAtHead(13.99);
bluprint.price.insertAtHead(11.99);
bluprint.price.insertAtHead(10.25);
bluprint.price.insertAtHead(15.99);
bluprint.price.insertAtHead(39.99);
bluprint.price.insertAtHead(5.99);
bluprint.price.insertAtHead(3.99);
bluprint.price.insertAtHead(5.65);
bluprint.price.insertAtHead(15.25);
bluprint.price.insertAtHead(23.45);
bluprint.price.insertAtHead(10.25);
bluprint.price.insertAtHead(6.99);
bluprint.price.insertAtHead(12.99);
bluprint.price.insertAtHead(12.82);
bluprint.price.insertAtHead(15.59);
bluprint.price.insertAtHead(14.99);
bluprint.price.insertAtHead(35.99);
bluprint.price.insertAtHead(20.00);
bluprint.price.insertAtHead(6.45);
bluprint.price.insertAtHead(13.99);
bluprint.price.insertAtHead(25.89);

bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_1.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_2.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_3.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_4.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_5.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_6.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_7.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_8.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_9.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_10.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_11.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_12.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_13.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_14.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_15.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_16.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_17.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_18.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_19.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_20.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_21.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_22.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_23.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_24.jpg`);
bluprint.img.insertAtHead(`../IMG/Store Products/Store 1/Product_25.jpg`);

bluprint.description.insertAtHead('Light Gray Palmer Hoodie');
bluprint.description.insertAtHead('White Palmer T-Shirt - Hustlers');
bluprint.description.insertAtHead('Keke Palmer Duvet Set (Purple)');
bluprint.description.insertAtHead('Keke Palmer Duvet Set (Tan)');
bluprint.description.insertAtHead('Keke Palmer T-Shirt (White)');
bluprint.description.insertAtHead('Keke Do You Love Me T-Shirt');
bluprint.description.insertAtHead('Black and Brown Exfoliating Cleanser');
bluprint.description.insertAtHead('African Clarifying Mud Mask Oils and Spray');
bluprint.description.insertAtHead('Skin Safe Manscaping Trimmer');
bluprint.description.insertAtHead('Hair Sponge Brush for Twists and Locks (Black)');
bluprint.description.insertAtHead('Classic Styling Essential Compact Comb (Black)');
bluprint.description.insertAtHead('Hair Brush Wooden Paddle Hairbrush Detangling Hairbrush');
bluprint.description.insertAtHead('Savanna Grass - Album By Kes');
bluprint.description.insertAtHead('Nyraju Natural Skincare Serum For Acne (Cleanser and Toner)');
bluprint.description.insertAtHead('Blueberry Bliss Curl Control Jelly');
bluprint.description.insertAtHead('African  Black Soap 6 fl oz');
bluprint.description.insertAtHead('Curl Love Moisture Milk (Rice Milk and Macadamia Oil)');
bluprint.description.insertAtHead('Hair Picks (3 Count)');
bluprint.description.insertAtHead('Conditioner, Treatment, Detangling Spray, and Shampoo');
bluprint.description.insertAtHead('Buttah AHA | BHA Rosewater Toner');
bluprint.description.insertAtHead('Champion Adult Mens Everyday Comfort Boxer Underwear');
bluprint.description.insertAtHead('Womens Comfort Stretch Brief Panties (Black)');
bluprint.description.insertAtHead('Womens Underwear Soft Breathable Panties Stretch Hipsters (Black)');
bluprint.description.insertAtHead('Mens Black Boxer Briefs Cotton Stretchy Underwear (5 Pack)');
bluprint.description.insertAtHead('Womens Padded Butt Lifter Hip Enhancer Shaper Panties Underwear');

bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);
bluprint.productLink.insertAtHead(`#`);

bluprint.storeNavigation.innerHTML = bluprint.getNavigator(0);
bluprint.newNavigations(0);

bluprint.createProducts(bluprint.img, 4103);
bluprint.displayProducts();
bluprint.setNumProducts(bluprint.myProductArray.length);
bluprint.sortList();
bluprint.setDocName("Palmer Studios Store | Page 1");
console.log(bluprint.myProductArray);