import * as bluprint from "../JAVASCRIPT/Store_Blueprint.js";
import {} from "../JAVASCRIPT/Nav&Footer_Blueprint.js";

// Product Attributes
blueprint.price.insertAtHead(59.99);
blueprint.price.insertAtHead(59.99);
blueprint.price.insertAtHead(32.98);
blueprint.price.insertAtHead(24.99);
blueprint.price.insertAtHead(47.89);
blueprint.price.insertAtHead(59.99);
blueprint.price.insertAtHead(22.89);
blueprint.price.insertAtHead(58.99);
blueprint.price.insertAtHead(19.99);
blueprint.price.insertAtHead(49.99);
blueprint.price.insertAtHead(4.99);
blueprint.price.insertAtHead(4.99);
blueprint.price.insertAtHead(4.99);
blueprint.price.insertAtHead(4.99);
blueprint.price.insertAtHead(4.99);
blueprint.price.insertAtHead(4.99);
blueprint.price.insertAtHead(19.99);
blueprint.price.insertAtHead(249.99);
blueprint.price.insertAtHead(67.89);
blueprint.price.insertAtHead(4.65);
blueprint.price.insertAtHead(59.99);
blueprint.price.insertAtHead(34.95);
blueprint.price.insertAtHead(22.89);
blueprint.price.insertAtHead(8.59);
blueprint.price.insertAtHead(10.99);

blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_1.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_2.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_3.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_4.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_5.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_6.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_7.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_8.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_9.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_10.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_11.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_12.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_13.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_14.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_15.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_16.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_17.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_18.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_19.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_20.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_21.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_22.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_23.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_24.jpg`);
blueprint.img.insertAtHead(`../IMG/Store Products/Store 3/Product_25.jpg`);

blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');
blueprint.description.insertAtHead('');

blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.storeName[0].remove();
blueprint.storeAd[0].remove();
blueprint.body[0].classList.add("changeBody");
blueprint.productMainContainer.classList.add('positionMain');
blueprint.storeNavigation.innerHTML = blueprint.getNavigator(2);
blueprint.newNavigations(2);
blueprint.createProducts(blueprint.img, 2842);
blueprint.displayProducts();
blueprint.setNumProducts(blueprint.myProductArray.length);
blueprint.setDocName("Palmer Studios Store | Page 3");