import * as blueprint from "../Store/Store_Blueprint.js";
import { companyInfo, navLinks, icons, attribute, navbar, footer, footerForm, footerInput, footerLabel, footerResponse, footerBtn } from "../Nav&Footer_Blueprint.js";

// Product Attributes
blueprint.price.insertAtHead(42.99);
blueprint.price.insertAtHead(13.99);
blueprint.price.insertAtHead(2.99);
blueprint.price.insertAtHead(10.99);
blueprint.price.insertAtHead(13.99);
blueprint.price.insertAtHead(7.99);
blueprint.price.insertAtHead(1129.99);
blueprint.price.insertAtHead(4.99);
blueprint.price.insertAtHead(15.99);
blueprint.price.insertAtHead(69.99);
blueprint.price.insertAtHead(56.99);
blueprint.price.insertAtHead(43.99);
blueprint.price.insertAtHead(28.49);
blueprint.price.insertAtHead(15.25);
blueprint.price.insertAtHead(16.59);
blueprint.price.insertAtHead(49.99);
blueprint.price.insertAtHead(49.99);
blueprint.price.insertAtHead(7.99);
blueprint.price.insertAtHead(12.82);
blueprint.price.insertAtHead(15.59);
blueprint.price.insertAtHead(125);
blueprint.price.insertAtHead(16.99);
blueprint.price.insertAtHead(20.00);
blueprint.price.insertAtHead(46.99);
blueprint.price.insertAtHead(24.99);
blueprint.price.insertAtHead(3590.89);
blueprint.price.insertAtHead(20.00);

blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_27.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_1.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_2.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_3.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_4.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_5.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_6.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_7.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_8.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_9.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_10.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_11.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_12.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_13.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_14.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_15.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_16.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_17.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_18.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_19.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_20.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_21.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_22.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_23.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_24.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_25.jpg`);
blueprint.img.insertAtHead(`/IMG/Store Products/Store 2/Product_4.jpg`);

blueprint.description.insertAtHead('Black African American Heritage Flag');
blueprint.description.insertAtHead('Black Lives Matter T-Shirt | Black');
blueprint.description.insertAtHead('Black Lives Matter Wristbands');
blueprint.description.insertAtHead('Black Lives Matter Metal Souvenir');
blueprint.description.insertAtHead('Black Lives Matter T-Shirt | Cotton Material');
blueprint.description.insertAtHead('Black Lives Matter Face Mask');
blueprint.description.insertAtHead('Canon 6D Mark II Camera with EF 24-105mm USM Lens, WiFi Enabled | Matt Black');
blueprint.description.insertAtHead('Professional Black Carbon Fiber Hair Combs Salon Grade Combo Comb Set');
blueprint.description.insertAtHead('Mens Turtleneck Slim Top | Black');
blueprint.description.insertAtHead('Beautiful Womens Solid Slim Bodysuit Outfit');
blueprint.description.insertAtHead('Solid Turtleneck Bodycon Dress');
blueprint.description.insertAtHead('Solid Outdoor Slim Dress');
blueprint.description.insertAtHead('TROJAN Pleasure Pack, 40 Assorted Condoms');
blueprint.description.insertAtHead('Durex Real Feel Non-Latex Condoms');
blueprint.description.insertAtHead('Trojan ENZ Condoms For Contraception Plus STI Protection, 36 Count, 1 Pack');
blueprint.description.insertAtHead('Taylor All Star Lift Platform Leather Converse | Black');
blueprint.description.insertAtHead('Taylor All Star Lift Platform Leather Converse | White');
blueprint.description.insertAtHead(`Smart & Sexy Women's Signature Lace Unlined Underwire Longline Bra`);
blueprint.description.insertAtHead('KY - Liquid Water-Based Personal Lubricant');
blueprint.description.insertAtHead('Acqua Di Gio Giorgio Armani Profumo');
blueprint.description.insertAtHead('Nike - Air Jordan 1 Mid');
blueprint.description.insertAtHead('Black Lives Matter Beaded Bracelet');
blueprint.description.insertAtHead('African Dashiki - White | Forest Green Triangle Design African Suiting and Cotton Fabrics');
blueprint.description.insertAtHead('African Dashiki - Forest Green | African Lace, Suiting, and Cotton Fabric');
blueprint.description.insertAtHead('African Dashiki - Orange | African Print Brocade, Silk, Lace, Suiting, and Cotton Fabric');
blueprint.description.insertAtHead('Dimond Wedding Ring');
blueprint.description.insertAtHead('Black Lives Matter T-Shirt');

blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);
blueprint.productLink.insertAtHead(`#`);

blueprint.storeName[0].remove();
blueprint.storeAd[0].remove();
blueprint.body[0].classList.add("changeBody");
blueprint.productMainContainer.classList.add('positionMain');
blueprint.storeNavigation.innerHTML = blueprint.getNavigator(1);
blueprint.newNavigations(1);
blueprint.createProducts(blueprint.img, 3846);
blueprint.displayProducts();
blueprint.setNumProducts(blueprint.myProductArray.length);
blueprint.setDocName("Palmer Studios Store | Page 2");

console.log(blueprint.myProductArray);